- .circleci/config.yml
- Dockerfile
- build.sh
- config/default.js
- connect/config.js
- deploy.sh
- src/app.js
- src/controllers/HealthController.js
- src/routes.js
> Dev circleci br1

- src/services/NotificationService.js
[Issue 1466 in connect-app](https://github.com/appirio-tech/connect-app/issues/1466) - Respect notification settings when displaying notifications
NOTE: looks like a lot of changes but I’ve just moved settings related methods to the top of file, to satisfy linter
> Issue 1466 in connect-app - Respect notification settings when displaying notifications

- connect/connectNotificationServer.js
Issue [1545](https://github.com/appirio-tech/connect-app/issues/1545) of Connect App - Skip notifications for managers
Didn't fix existent lint errors in another files, as already fixed them in another PR
> Issue 1545 of Connect App - Skip notifications for managers

- connect/connectNotificationServer.js
Issue #9 - Notifications from CoderBot are not created correctly
> Issue #9 - Notifications from CoderBot are not created correctly

- connect/config.js
- connect/events-config.js
- src/app.js
- src/models/index.js
Issue [1545](https://github.com/appirio-tech/connect-app/issues/1545) of Connect App - Skip notifications for managers - missed files
Fix lint errors
> Issue 1545 of Connect App - Skip notifications for managers - missed files

- src/app.js
Should be merged after bus api old format is deprecated
@sachin-maheshwari
> upgrade bus api format

- connect/events-config.js
This is related to https://github.com/topcoder-platform/tc-project-service/pull/110.
> Added more events for which to create notifications about

- connect/connectNotificationServer.js
> patching runtime error

- connect/notificationServices/email.js
- deploy.sh
> Increasing resources and patch for handling immediately setting

- connect/connectNotificationServer.js
> Github issue#81, Empty email for new project links

- connect/notificationServices/email.js
Testing in production directly as it seems m2m thing is not working in dev right now
> Sending project invite emails immediately

- connect/service.js
- src/common/tcApiHelper.js
fix for issue https://github.com/topcoder-platform/tc-notifications/issues/121
> properly quote and escape query to member service

- connect/service.js
- src/common/tcApiHelper.js
hotfix for issue https://github.com/topcoder-platform/tc-notifications/issues/121
> [Hotfix] - properly quote and escape query to member service

- config/default.js
- docs/swagger_api.yaml
- docs/tc-notification-server-api.postman_collection.json
- package.json
- src/common/tcApiHelper.js
- src/controllers/NotificationController.js
- src/routes.js
- src/services/NotificationService.js
Reverts topcoder-platform/tc-notifications#132
> Revert "V5 API standards"

- emails/src/partials/invites.html
Email templates for invites are updated to send SSO section only to users where isSSO flag is set
FYI @RishiRajSahu
> SSO user invite emails update

- connect/notificationServices/email.js
@maxceem Could you please review this PR?
> Fixing old links in email notifications

- connect/notificationServices/email.js
> Hotfix/post release 2.4.13.1

- connect/connectNotificationServer.js
- connect/notificationServices/email.js
Fix for the issue which is tracked in Connect App https://github.com/appirio-tech/connect-app/issues/3216
Additionally, make a fix for a potential issue. See [commit message](https://github.com/topcoder-platform/tc-notifications/commit/9498198e468d00fab0aa2892a605d7f8103d29b4) for details.
> [Hotfix] [Prod] fix duplicates in emails

- emails/src/partials/project-team.html
- emails/src/styles/main.css
- emails/src/styles/partials/_base.scss
- make the second button height and width more accurately match the primary button size
- rename some classes to have more clear names
> fix: improved "Join Project" and "Decline" link styles in emails

- .circleci/config.yml
- README.md
- connect/config.js
- connect/connectNotificationServer.js
- connect/service.js
- package.json
- tools/resetDb.js
> Production release - Use Projects V5

- emails/src/partials/project-team.html
fixes https://github.com/appirio-tech/connect-app/issues/3486
> issue 3486 fix 

- emails/src/partials/project-team.html
Fixes that have been done during Bug Bash challenge in Connect App.
1. As email template has been updated, it should be rebuilt and updated at SendGrid.
> Cf20 [WIP]

- emails/src/partials/invites.html
Updated registration URL for email invite
fyi @vikasrohit
> Supporting Release - Connect Release 2.11.1

- .circleci/config.yml
- connect/config.js
- emails/src/partials/invites.html
> [PATCH][DEV]changes to update reg url to new auth0

- README.md
- config/default.js
- connect/config.js
- connect/connectNotificationServer.js
- constants.js
- docs/tc-notifications.postman_collection.json
- docs/tc-notifications.postman_environment.json
- package-lock.json
- src/app.js
- src/common/tcApiHelper.js
- src/controllers/NotificationController.js
- src/hooks/hookBulkMessage.js
- src/hooks/index.js
- src/models/BulkMessageUserRefs.js
- src/processors/broadcast/bulkNotificationHandler.js
- src/processors/index.js
- src/processors/universal/universalNotificationHandler.js
- src/services/NotificationService.js
- src/services/UniversalNotificationService.js
- test/checkHooks.js
Universal Notification implementation as per challenge specification https://www.topcoder.com/challenges/c7c453c9-5a2e-4452-8dfd-0ea6c0ef26c9.
> adding new universal notification service
